/**
 * The precipitation path, steps 5 and 6.
 *
 * The shipped golden fixtures stop at step 4: a fixture's `series` is the
 * seasonal cycle plus the EOF projection, with the baseline and the gamma
 * quantile mapping left out. So the two steps unique to `pr` — the ones that
 * put the answer in the right units — are not covered by the fixtures at all.
 *
 * `test/fixtures/pr_transform_reference.json` closes that gap: it is METEOR's
 * own `apply_transform_from_bundle` run over the fixture's PCs, regenerated by
 * `scripts/make_transform_reference.py`.
 */

import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { Bundle, GoldenFixture } from '../src/lib/bundle.js';
import { annualToMonthly, applyTransform, forcedResponse } from '../src/lib/kernel.js';
import { erfc, interp, normalCdf, normalGenerator } from '../src/lib/stats.js';

const DATA = new URL('../data/', import.meta.url);

const bundle = new Bundle(readFileSync(new URL('meteor_NorESM2-MM_pr_bundle_v1.nc', DATA)));
const fixture = new GoldenFixture(
  readFileSync(new URL('meteor_NorESM2-MM_pr_golden_ssp245_v1.nc', DATA))
);
const reference = JSON.parse(
  readFileSync(new URL('./fixtures/pr_transform_reference.json', import.meta.url))
);

describe('precipitation transform', () => {
  it('carries a gamma transform and its fitted window', () => {
    expect(bundle.hasTransform).toBe(true);
    expect(bundle.attrs.transform_type).toBe('gamma');
    expect(bundle.transformWindow).toEqual([2015, 2100]);
  });

  it('reproduces METEOR end to end, baseline and quantile mapping included', () => {
    const forcing = bundle.forcing(reference.scenario);
    const offset = reference.start_year - bundle.forcingYearStart;
    const nMonths = fixture.nMonths;
    const nYears = nMonths / 12;

    for (const [i, location] of fixture.locations.entries()) {
      const forced = forcedResponse(bundle, location, forcing);
      const monthly = annualToMonthly(forced.subarray(offset, offset + nYears), nMonths);
      const baseline = bundle.get('transform_baseline')[bundle.locationIndex(location)];

      const realizations = [];
      for (let r = 0; r < fixture.nRealizations; r += 1) {
        const series = fixture.series(i, r);
        realizations.push(
          Float64Array.from(series, (v, t) => v + monthly[t] + baseline)
        );
      }

      const actual = applyTransform(bundle, location, realizations);
      const expected = reference.values[location];

      // Transformed precipitation is strictly positive and of order 1e-5;
      // compare relative to the location's own magnitude.
      let scale = 0;
      for (const row of expected) for (const v of row) scale = Math.max(scale, Math.abs(v));

      let worst = 0;
      for (let r = 0; r < expected.length; r += 1) {
        for (let t = 0; t < nMonths; t += 1) {
          worst = Math.max(worst, Math.abs(actual[r][t] - expected[r][t]) / scale);
        }
      }
      // Tighter than the fixture comparisons, because nothing here is stored
      // at float32: both sides read the same bundle arrays and differ only in
      // the normal CDF and the interpolation arithmetic.
      expect(worst, location).toBeLessThan(1e-10);
    }
  });

  it('produces strictly positive precipitation', () => {
    for (const rows of Object.values(reference.values)) {
      for (const row of rows) {
        for (const v of row) expect(v).toBeGreaterThan(0);
      }
    }
  });

  it('refuses a bundle with no transform', () => {
    const tas = new Bundle(readFileSync(new URL('meteor_NorESM2-MM_tas_bundle_v1.nc', DATA)));
    expect(tas.hasTransform).toBe(false);
    expect(() => applyTransform(tas, 'global', [new Float64Array(12)])).toThrow(
      /no distribution transform/
    );
  });
});

describe('numerical primitives', () => {
  it('matches known normal CDF values', () => {
    // Reference values from scipy.stats.norm.cdf.
    expect(normalCdf(0)).toBeCloseTo(0.5, 12);
    expect(normalCdf(1)).toBeCloseTo(0.8413447460685429, 14);
    expect(normalCdf(-1)).toBeCloseTo(0.15865525393145707, 14);
    expect(normalCdf(1.96)).toBeCloseTo(0.9750021048517795, 14);
    expect(normalCdf(-3.5)).toBeCloseTo(0.00023262907903552502, 15);
  });

  it('keeps erfc symmetric', () => {
    for (const x of [0.1, 0.5, 1, 2, 3]) {
      expect(erfc(x) + erfc(-x)).toBeCloseTo(2, 10);
    }
  });

  it('interpolates linearly and clamps outside the grid', () => {
    const xp = [0, 1, 2];
    const fp = [0, 10, 20];
    expect(interp(0.5, xp, fp)).toBeCloseTo(5, 12);
    expect(interp(1.75, xp, fp)).toBeCloseTo(17.5, 12);
    // numpy.interp clamps rather than extrapolating.
    expect(interp(-1, xp, fp)).toBe(0);
    expect(interp(99, xp, fp)).toBe(20);
  });

  it('draws reproducible standard normals', () => {
    const first = normalGenerator(42);
    const second = normalGenerator(42);
    const a = Array.from({ length: 5 }, () => first());
    const b = Array.from({ length: 5 }, () => second());
    expect(a).toEqual(b);

    const draws = Array.from({ length: 20000 }, () => normalGenerator(7)());
    const sample = Array.from({ length: 20000 }, () => first());
    const mean = sample.reduce((s, v) => s + v, 0) / sample.length;
    const variance =
      sample.reduce((s, v) => s + (v - mean) ** 2, 0) / sample.length;
    expect(mean).toBeCloseTo(0, 1);
    expect(variance).toBeCloseTo(1, 1);
    expect(draws.length).toBe(20000);
  });
});
